/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "lcd.h"
#include "stm32f103c6_gpio_driver.h"
#include "stm32f103x6.h"
#include "stm32f103c6_EXTI_driver.h"
 void delay (int time)
{
	unsigned int i,j;
	for(i=0;i<time;i++)
	{
		for(j=0;j<255;j++)
		{
		}
	}
}
void enable_clock()
{
RCC_GPIOA_CLK_EN();
RCC_GPIOB_CLK_EN();
RCC_AFIO_CLK_EN();
}
void EXTI9PB9_callback(void)
{
LCD_WRITE_STRING("IRQ EXTI9 IS HAPPENED _|-");
delay(1000);
LCD_Clear_Screen();

}
int main()
{
	enable_clock();
	LCD_init();
	EXTI_Pin_Config_t EXTI_Cfg;
	EXTI_Cfg.EXTI_Pin=EXTI9PB9;
	EXTI_Cfg.trigger_case=EXTI_trigger_rising;
	EXTI_Cfg.P_IRQ_Callback=EXTI9PB9_callback;
	EXTI_Cfg.IRQ_EN=EXTI_IRQ_enable;
	MCAL_GPIO_EXTI_init(&EXTI_Cfg);
	while(1)
	{

	}

}
