/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "../stm32_f103c6_drivers/inc/stm32f103c6_gpio_driver.h"
#include "../stm32_f103c6_drivers/inc/stm32f103x6.h"
//TO initialize the clock for the APB2 Bus
void clock_init(void)
{
	//Enabling the clock to APB2 bus GPIOA
	RCC_GPIOA_CLK_EN();
	//Enabling the clock to APB2 bus GPIOB
	RCC_GPIOB_CLK_EN();
}
//TO initialize the GPIOA and Pin 13
void gpio_init()
{
	//determine the configuration of the pin
	GPIO_Pin_config_t pinconfig;
	//PA1 Floating input
	pinconfig.GPIO_Pin_number=GPIO_PIN_1;
	pinconfig.GPIO_mode_define=GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_INIT(GPIOA, &pinconfig);
	//PB1 push pull output
	pinconfig.GPIO_Pin_number=GPIO_PIN_1;
	pinconfig.GPIO_mode_define=GPIO_MODE_OUTPUT_PP;
	pinconfig.GPIO_output_speed=GPIO_speed_10M;
	MCAL_GPIO_INIT(GPIOB, &pinconfig);
	//PA13 Floating input
	pinconfig.GPIO_Pin_number=GPIO_PIN_13;
	pinconfig.GPIO_mode_define=GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_INIT(GPIOA, &pinconfig);
	//PB13 push pull output
	pinconfig.GPIO_Pin_number=GPIO_PIN_13;
	pinconfig.GPIO_mode_define=GPIO_MODE_OUTPUT_PP;
	pinconfig.GPIO_output_speed=GPIO_speed_10M;
	MCAL_GPIO_INIT(GPIOB, &pinconfig);
}

void wait ()
{
	unsigned int i,j;
	for(i=0;i<100;i++)
	{
		for(j=0;j<255;j++)
		{

		}
	}
}
int main(void)
{

	clock_init();
	gpio_init();

	while(1)
	{
//		MCAL_GPIO_toggle_Pin(GPIOB, GPIO_PIN_13);
//		wait();
//		MCAL_GPIO_toggle_Pin(GPIOB, GPIO_PIN_13);
//		wait();
//		MCAL_GPIO_toggle_Pin(GPIOB, GPIO_PIN_1);
//		wait();
//		MCAL_GPIO_toggle_Pin(GPIOB, GPIO_PIN_1);
//		wait();

		//PA1>> PULL UP RESISTOR
		if(MCAL_GPIO_Read_Pin(GPIOA,GPIO_PIN_1)==0)//single press
		{
			MCAL_GPIO_toggle_Pin(GPIOB,GPIO_PIN_1);
			while(MCAL_GPIO_Read_Pin(GPIOA,GPIO_PIN_1)==0);
		}
		//PA13>> PULL DOWN RESISTOR
		if(MCAL_GPIO_Read_Pin(GPIOA,GPIO_PIN_13)==1)//multi press
			{
				MCAL_GPIO_toggle_Pin(GPIOB,GPIO_PIN_13);
			}
			wait();
	}
}
